# Generated by Django 6.0.1 on 2026-01-26 18:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='current_mood',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='mood_updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
