# Generated by Django 6.0.1 on 2026-01-26 19:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_user_current_mood_user_mood_updated_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='rule',
            name='priority',
            field=models.CharField(choices=[('High', 'High'), ('Medium', 'Medium'), ('Low', 'Low')], default='Medium', max_length=10),
        ),
    ]
