# Generated by Django 6.0.1 on 2026-01-28 04:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_rule_priority'),
    ]

    operations = [
        migrations.AddField(
            model_name='couple',
            name='invite_code',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
