# Generated by Django 6.0.1 on 2026-02-12 16:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_bucketitem_lovenote'),
    ]

    operations = [
        migrations.CreateModel(
            name='DateIdea',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('category', models.CharField(choices=[('romantic', 'Romantic'), ('adventure', 'Adventure'), ('cozy', 'Cozy Night In'), ('budget', 'Budget-Friendly'), ('luxury', 'Luxury'), ('active', 'Active/Sports'), ('cultural', 'Cultural'), ('foodie', 'Foodie')], max_length=20)),
                ('budget', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('is_completed', models.BooleanField(default=False)),
                ('completed_date', models.DateField(blank=True, null=True)),
                ('rating', models.IntegerField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('couple', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='date_ideas', to='api.couple')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_date_ideas', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='GratitudeEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField()),
                ('date', models.DateField(auto_now_add=True)),
                ('is_read', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gratitude_entries', to=settings.AUTH_USER_MODEL)),
                ('couple', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gratitude_entries', to='api.couple')),
            ],
            options={
                'verbose_name_plural': 'Gratitude Entries',
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='LoveLanguageAction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language_type', models.CharField(choices=[('words', 'Words of Affirmation'), ('acts', 'Acts of Service'), ('gifts', 'Receiving Gifts'), ('quality', 'Quality Time'), ('touch', 'Physical Touch')], max_length=20)),
                ('description', models.TextField()),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('couple', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='love_actions', to='api.couple')),
                ('giver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='given_love_actions', to=settings.AUTH_USER_MODEL)),
                ('receiver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='received_love_actions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='LoveLanguage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('primary_language', models.CharField(choices=[('words', 'Words of Affirmation'), ('acts', 'Acts of Service'), ('gifts', 'Receiving Gifts'), ('quality', 'Quality Time'), ('touch', 'Physical Touch')], max_length=20)),
                ('secondary_language', models.CharField(blank=True, choices=[('words', 'Words of Affirmation'), ('acts', 'Acts of Service'), ('gifts', 'Receiving Gifts'), ('quality', 'Quality Time'), ('touch', 'Physical Touch')], max_length=20)),
                ('quiz_completed', models.BooleanField(default=False)),
                ('quiz_completed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('couple', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='love_languages', to='api.couple')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='love_language', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('couple', 'user')},
            },
        ),
    ]
