# Generated by Django 6.0.1 on 2026-02-24 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_user_profile_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='couple',
            name='anniversary_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
