# Generated by Django 6.0.1 on 2026-02-24 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_couple_anniversary_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='couple',
            name='anniversary_date',
        ),
        migrations.AddField(
            model_name='couple',
            name='anniversary_start',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
