# Generated by Django 6.0.1 on 2026-02-27 17:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0014_announcementpopup_contactmessage_coupon_dailyvisit_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='announcementpopup',
            name='display_frequency',
            field=models.CharField(choices=[('once', 'Once per user forever'), ('session', 'Once per session (until tab closed)'), ('every_time', 'Every time dashboard loads')], default='session', max_length=20),
        ),
    ]
