# Generated by Django 6.0.1 on 2026-02-27 17:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0015_announcementpopup_display_frequency'),
    ]

    operations = [
        migrations.AddField(
            model_name='announcementpopup',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='popups/'),
        ),
    ]
