# Generated by Django 6.0.1 on 2026-02-27 20:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0017_bucketitem_latitude_bucketitem_longitude'),
    ]

    operations = [
        migrations.AddField(
            model_name='couple',
            name='theme_color',
            field=models.CharField(default='rose', max_length=50),
        ),
    ]
