# Generated by Django 6.0.1 on 2026-02-28 19:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0018_couple_theme_color'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bucketitem',
            name='latitude',
        ),
        migrations.RemoveField(
            model_name='bucketitem',
            name='longitude',
        ),
        migrations.AddField(
            model_name='bucketitem',
            name='category',
            field=models.CharField(choices=[('travel', 'Travel & Trips'), ('adventure', 'Adventure & Outdoor'), ('food', 'Dining & Food'), ('romance', 'Romantic Dates'), ('experience', 'Life Experiences'), ('home', 'Home & Living'), ('other', 'Something Else')], default='other', max_length=20),
        ),
    ]
