# Generated by Django 6.0.1 on 2026-02-28 20:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0020_contactmessage_phone_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='contactmessage',
            name='address',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='contactmessage',
            name='country',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
