# Generated by Django 6.0.1 on 2026-03-07 16:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0025_alter_supportticket_status_ticketmessage_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='supportticket',
            name='resolved_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
