# Generated by Django 6.0.1 on 2026-03-08 11:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0027_sitesetting_user_email_verified_verificationcode'),
    ]

    operations = [
        migrations.AlterField(
            model_name='couple',
            name='invite_code',
            field=models.CharField(blank=True, max_length=10, null=True, unique=True),
        ),
        migrations.DeleteModel(
            name='InviteCode',
        ),
    ]
