# Generated by Django 6.0.1 on 2026-03-17 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0029_countdown'),
    ]

    operations = [
        migrations.AddField(
            model_name='countdown',
            name='is_notified',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='countdown',
            name='is_pinned',
            field=models.BooleanField(default=False),
        ),
    ]
