# Generated by Django 6.0.1 on 2026-02-27 19:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('api', '0016_announcementpopup_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserSubscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tier', models.CharField(choices=[('FREE', 'Free'), ('PREMIUM', 'Premium'), ('ULTRA', 'Ultra')], default='FREE', max_length=20)),
                ('status', models.CharField(choices=[('PENDING_APPROVAL', 'Pending Approval'), ('ACTIVE', 'Active'), ('EXPIRED', 'Expired'), ('REJECTED', 'Rejected')], default='ACTIVE', max_length=20)),
                ('start_date', models.DateTimeField(auto_now_add=True)),
                ('end_date', models.DateTimeField(blank=True, null=True)),
                ('payment_screenshot', models.ImageField(blank=True, null=True, upload_to='payment_screenshots/')),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('applied_coupon', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.coupon')),
                ('couple', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='subscription', to='api.couple')),
            ],
        ),
    ]
