# Generated by Django 6.0.1 on 2026-02-27 21:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0002_paymentsettings'),
    ]

    operations = [
        migrations.AddField(
            model_name='usersubscription',
            name='transaction_id',
            field=models.CharField(blank=True, help_text='Reference ID from the payment app', max_length=100, null=True),
        ),
    ]
