# Generated by Django 6.0.1 on 2026-03-25 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0003_usersubscription_transaction_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='usersubscription',
            name='plan_duration',
            field=models.CharField(blank=True, choices=[('MONTHLY', '1 Month'), ('YEARLY', '1 Year'), ('LIFETIME', 'Lifetime')], default='MONTHLY', max_length=20, null=True),
        ),
    ]
