# Generated by Django 6.0.1 on 2026-04-16 16:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0004_usersubscription_plan_duration'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paymentsettings',
            name='upi_id',
            field=models.CharField(default='Q836094841@ybl', max_length=100),
        ),
    ]
