# Generated by Django 6.0.1 on 2026-02-27 20:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('api', '0017_bucketitem_latitude_bucketitem_longitude'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Expense',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('date', models.DateField(auto_now_add=True)),
                ('category', models.CharField(choices=[('dates', 'Date Nights'), ('travel', 'Travel & Trips'), ('food', 'Groceries & Food'), ('bills', 'Shared Bills'), ('other', 'Other')], default='other', max_length=20)),
                ('split_type', models.CharField(choices=[('50/50', 'Split 50/50'), ('payer_full', 'Payer Paid Full'), ('other', 'Custom')], default='50/50', max_length=20)),
                ('couple', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='expenses', to='api.couple')),
                ('payer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='paid_expenses', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='GiftIdea',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('price_estimate', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('url', models.URLField(blank=True)),
                ('for_event', models.CharField(blank=True, help_text='e.g. Birthday, Anniversary', max_length=100)),
                ('event_date', models.DateField(blank=True, null=True)),
                ('is_purchased', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('couple', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gift_ideas', to='api.couple')),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_gifts', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
