# Generated by Django 6.0.1 on 2026-02-27 20:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('api', '0016_announcementpopup_image'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Badge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('icon_name', models.CharField(help_text='Lucide icon name', max_length=50)),
                ('badge_type', models.CharField(choices=[('streak', 'Daily Streak'), ('milestone', 'Milestone Achievement'), ('engagement', 'Engagement Badge')], max_length=50)),
                ('requirement_value', models.PositiveIntegerField(help_text='Value to reach for this badge')),
            ],
        ),
        migrations.CreateModel(
            name='QuizQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=500)),
                ('category', models.CharField(default='General', max_length=100)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Streak',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('current_streak', models.PositiveIntegerField(default=0)),
                ('longest_streak', models.PositiveIntegerField(default=0)),
                ('last_interaction_date', models.DateField(blank=True, null=True)),
                ('couple', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='streak', to='api.couple')),
            ],
        ),
        migrations.CreateModel(
            name='CoupleBadge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('earned_at', models.DateTimeField(auto_now_add=True)),
                ('badge', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='earned_by', to='gamification.badge')),
                ('couple', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='badges', to='api.couple')),
            ],
            options={
                'unique_together': {('couple', 'badge')},
            },
        ),
        migrations.CreateModel(
            name='QuizAnswer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('my_own_answer', models.TextField(help_text='My own answer to this question')),
                ('guess_partner_answer', models.TextField(help_text='What I think my partner will say')),
                ('answered_at', models.DateTimeField(auto_now_add=True)),
                ('couple', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quiz_answers', to='api.couple')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quiz_answers', to=settings.AUTH_USER_MODEL)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='gamification.quizquestion')),
            ],
            options={
                'unique_together': {('question', 'couple', 'user')},
            },
        ),
    ]
